name: "Workflow Dispatch"
description: "Trigger and chain GitHub Actions workflows with workflow_dispatch events"

inputs:
  workflow:
    description: "Name or ID of workflow to run"
    required: true
  token:
    description: "GitHub token with repo write access, can NOT use secrets.GITHUB_TOKEN, see readme"
    required: true
  ref:
    description: "The reference of the workflow run. The reference can be a branch, tag, or a commit SHA"
    required: true
  repo:
    description: "Repo owner & name, slash separated"
    required: true
  tag_input:
    description: "The `tag` input to pass to the workflow"
    required: true

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  color: orange
  icon: send
