name: Release
on:
  push:
    branches:
      - master

jobs:
  release-please:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.33.1
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: workflow-dispatch-action
          bump-minor-pre-major: true
